export const cards = [
  {
    id: 0,
    name: 'The Red Dragon',
    mana: 1,
    attack: 2,
    defense: 2,
    portrait: 'https://i.imgur.com/atJRh8b.jpg',
    description: 'The Red Dragon is a powerful creature with fiery scales and a fearsome presence. With a mana cost of 1, it can be summoned early in the game to unleash its impressive attack and defense abilities.',
    cardImage: '/cards/3.png',
    type: 'Minion',
  },
  {
    id: 1,
    name: 'Fire Phoenix',
    mana: 2,
    attack: 2,
    defense: 2,
    portrait: 'https://i.imgur.com/RvcO0pg.png',
    description: 'The Fire Phoenix is a majestic bird that rises from the flames. With a mana cost of 2, it possesses moderate attack and defense capabilities. Its fiery nature makes it a formidable ally in battles.',
    cardImage: '/cards/4.png',
    type: 'Minion',
  },
  {
    id: 2,
    name: 'Beetroot',
    mana: 1,
    attack: 2,
    defense: 2,
    portrait: 'https://i.imgur.com/TBeHnWo.jpg',
    description: 'Beetroot is a card with moderate attack and defense abilities. It has a mana cost of 1 and can provide strategic value in battles. However, it lacks any unique special abilities or characteristics.',
    cardImage: '/cards/5.png',
    type: 'Minion',
  },
  {
    id: 3,
    name: 'Carrot',
    mana: 1,
    attack: 1,
    defense: 2,
    portrait: 'https://i.imgur.com/smdtY1Y.jpg',
    description: 'Carrot is a low-cost card with relatively low attack but decent defense. It can serve as a cheap defensive option in battles, absorbing damage from enemy attacks.',
    cardImage: '/cards/6.png',
    type: 'Minion',
  },
  {
    id: 4,
    name: 'The Wizard Frog',
    mana: 3,
    attack: 4,
    defense: 3,
    portrait: 'https://i.imgur.com/JkZwHJG.jpg',
    description: 'The Wizard Frog is a magical creature with impressive attack and defense capabilities. With a mana cost of 3, it can be a key player in battles, casting powerful spells and conjuring defensive shields.',
    cardImage: '/cards/7.png',
    type: 'Minion',
  },
  {
    id: 5,
    name: 'Corgi',
    mana: 2,
    attack: 3,
    defense: 2,
    portrait: '/corgi.jpg',
    description: 'Corgi is a charming and agile card with moderate attack and defense abilities. With a mana cost of 2, it can swiftly navigate the battlefield and deliver swift strikes to opponents.',
    cardImage: '/cards/8.png',
    type: 'Minion',
  },
  {
    id: 6,
    name: 'Octopus',
    mana: 2,
    attack: 3,
    defense: 2,
    portrait: 'https://i.imgur.com/oEO2hjC.jpg',
    description: 'Octopus is a versatile creature that excels at adapting to different situations. With a mana cost of 2, it can use its tentacles to both attack and defend, providing flexibility in battles.',
    cardImage: '/cards/9.png',
    type: 'Minion',
  },
  {
    id: 7,
    name: 'SSS Snake',
    mana: 2,
    attack: 3,
    defense: 2,
    portrait: 'https://i.imgur.com/98C2bwX.jpg',
    description: 'The SSS Snake is a stealthy and cunning card. With a mana cost of 2, it can strike swiftly and silently, bypassing enemy defenses. It has moderate attack and defense capabilities.',
    cardImage: '/cards/10.png',
    type: 'Minion',
  },
  {
    id: 8,
    name: 'The onion',
    mana: 3,
    attack: 4,
    defense: 3,
    portrait: 'https://i.imgur.com/JXVC7lU.png?1',
    description: 'The onion is a card with a peculiar set of abilities. With a mana cost of 3, it can make opponents shed tears with its potent attack and defense capabilities. It possesses an aura of protection that reduces incoming damage.',
    cardImage: '/cards/11.png',
    type: 'Minion',
  },
  {
    id: 9,
    name: 'Twin Mushrooms',
    mana: 4,
    attack: 5,
    defense: 2,
    portrait: 'https://i.imgur.com/g5lp5nC.jpg',
    description: 'Twin Mushrooms are a unique duo that act as a single card. With a mana cost of 4, they possess high attack power but relatively low defense. Their combined strength makes them a formidable force on the battlefield.',
    cardImage: '/cards/12.png',
    type: 'Minion',
  },
  {
    id: 10,
    name: 'Booo',
    mana: 4,
    attack: 5,
    defense: 3,
    portrait: 'https://i.imgur.com/xD2yWMl.jpg',
    description: 'Booo is a card that harnesses the power of fear. With a mana cost of 4, it can intimidate opponents with its haunting presence, reducing their attack power. It possesses high attack and decent defense abilities.',
    cardImage: '/cards/13.png',
    type: 'Minion',
  },
  {
    id: 11,
    name: 'Bee Bee',
    mana: 4,
    attack: 5,
    defense: 3,
    portrait: 'https://i.imgur.com/3RB2DYl.jpg',
    description: 'Bee Bee is a buzzing card that commands the power of a swarm. With a mana cost of 4, it can overwhelm opponents with its high attack and disrupt their strategies. It has decent defense to withstand retaliation.',
    cardImage: '/cards/14.png',
    type: 'Minion',
  },
  {
    id: 12,
    name: 'Poison Flower',
    mana: 5,
    attack: 5,
    defense: 4,
    portrait: 'https://i.imgur.com/6X8bwdM.jpg',
    description: 'The Poison Flower is a sinister and deadly card. With a mana cost of 5, it can poison enemies with its toxic attacks, gradually wearing them down. It possesses high attack and defense capabilities.',
    cardImage: '/cards/15.png',
    type: 'Minion',
  },
  {
    id: 13,
    name: 'The Sea Friends',
    mana: 3,
    attack: 4,
    defense: 3,
    portrait: 'https://i.imgur.com/zXnQO6n.jpg',
    description: 'The Sea Friends are a group of aquatic creatures that work together to defend the ocean. With a mana cost of 3, they have moderate attack and defense abilities. They excel in battles near water-based environments.',
    cardImage: '/cards/16.png',
    type: 'Minion',
  },
  {
    id: 14,
    name: 'Angry Cat',
    mana: 3,
    attack: 3,
    defense: 3,
    portrait: 'https://i.imgur.com/uSlX1eM.jpg',
    description: 'The Angry Cat is a ferocious feline with a short temper. With a mana cost of 3, it can unleash its fury on opponents, dealing significant damage. It possesses balanced attack and defense capabilities.',
    cardImage: '/cards/17.png',
    type: 'Minion',
  },
  {
    id: 15,
    name: 'Rocket',
    mana: 4,
    attack: 5,
    defense: 3,
    portrait: 'https://i.imgur.com/fXhdKwB.jpg',
    description: 'Rocket is an explosive card that brings firepower to the battlefield. With a mana cost of 4, it launches devastating attacks, obliterating enemy defenses. It has high attack power but relatively low defense.',
    cardImage: '/cards/18.png',
    type: 'Minion',
  },
];

export function newRandomCard() {
  const randomCard = cards[Math.floor(Math.random() * cards.length)];
  return randomCard;
}
