export const cards = [
  {
    id: 1,
    name: 'The Red Dragon',
    mana: 1,
    attack: 2,
    defense: 2,
    portrait: 'https://i.imgur.com/atJRh8b.jpg',
  },
  {
    id: 2,
    name: 'Fire Phoenix',
    mana: 2,
    attack: 2,
    defense: 2,
    portrait: 'https://i.imgur.com/RvcO0pg.png?1',
  },
  {
    id: 3,
    name: 'Beetroot',
    mana: 1,
    attack: 2,
    defense: 2,
    portrait: 'https://i.imgur.com/TBeHnWo.jpg',
  },
  {
    id: 4,
    name: 'Carrot',
    mana: 1,
    attack: 1,
    defense: 2,
    portrait: 'https://i.imgur.com/smdtY1Y.jpg',
  },
  {
    id: 5,
    name: 'The Wizard Frog',
    mana: 3,
    attack: 4,
    defense: 3,
    portrait: 'https://i.imgur.com/JkZwHJG.jpg',
  },
  {
    id: 6,
    name: 'Corgi',
    mana: 2,
    attack: 3,
    defense: 2,
    portrait: 'https://i.imgur.com/JkZwHJG.jpg',
  },
  {
    id: 7,
    name: 'Octopus',
    mana: 2,
    attack: 3,
    defense: 2,
    portrait: 'https://i.imgur.com/oEO2hjC.jpg',
  },
  {
    id: 8,
    name: 'SSS Snake',
    mana: 2,
    attack: 3,
    defense: 2,
    portrait: 'https://i.imgur.com/98C2bwX.jpg',
  },
  {
    id: 9,
    name: 'The onion',
    mana: 3,
    attack: 4,
    defense: 3,
    portrait: 'https://i.imgur.com/JXVC7lU.png?1',
  },
  {
    id: 10,
    name: 'Twin Mushrooms',
    mana: 4,
    attack: 5,
    defense: 2,
    portrait: 'https://i.imgur.com/g5lp5nC.jpg',
  },
  {
    id: 11,
    name: 'Booo',
    mana: 4,
    attack: 5,
    defense: 3,
    portrait: 'https://i.imgur.com/xD2yWMl.jpg',
  },
  {
    id: 12,
    name: 'Bee Bee',
    mana: 4,
    attack: 5,
    defense: 3,
    portrait: 'https://i.imgur.com/3RB2DYl.jpg',
  },
  {
    id: 13,
    name: 'Poison Flower',
    mana: 5,
    attack: 5,
    defense: 4,
    portrait: 'https://i.imgur.com/6X8bwdM.jpg',
  },
  {
    id: 14,
    name: 'The Sea Friends',
    mana: 3,
    attack: 4,
    defense: 3,
    portrait: 'https://i.imgur.com/zXnQO6n.jpg',
  },
  {
    id: 15,
    name: 'Angry Cat',
    mana: 3,
    attack: 3,
    defense: 3,
    portrait: 'https://i.imgur.com/uSlX1eM.jpg',
  },
  {
    id: 16,
    name: 'Rocket',
    mana: 4,
    attack: 5,
    defense: 3,
    portrait: 'https://i.imgur.com/fXhdKwB.jpg',
  },
];

export function newRandomCard() {
  const randomCard = cards[Math.floor(Math.random() * cards.length)];
  return randomCard;
}
