export const cards = [
  {
    id: 0,
    name: 'The Red Dragon',
    mana: 1,
    attack: 2,
    defense: 2,
    portrait: 'https://i.imgur.com/atJRh8b.jpg',
    description: 'The Red Dragon is a powerful creature with fiery scales and a fearsome presence. With a mana cost of 1, it can be summoned early in the game to unleash its impressive attack and defense abilities.',
    cardImage: '/cards/3.png',
    type: 'Minion',
  },
  {
    id: 1,
    name: 'Fire Phoenix',
    mana: 2,
    attack: 2,
    defense: 2,
    portrait: 'https://i.imgur.com/RvcO0pg.png',
    description: 'The Fire Phoenix is a majestic bird that rises from the flames. With a mana cost of 2, it possesses moderate attack and defense capabilities. Its fiery nature makes it a formidable ally in battles.',
    cardImage: '/cards/4.png',
    type: 'Minion',
  },
  {
    id: 2,
    name: 'Beetroot',
    mana: 1,
    attack: 2,
    defense: 2,
    portrait: 'https://i.imgur.com/TBeHnWo.jpg',
    description: 'Beetroot is a card with moderate attack and defense abilities. It has a mana cost of 1 and can provide strategic value in battles. However, it lacks any unique special abilities or characteristics.',
    cardImage: '/cards/5.png',
    type: 'Minion',
  },
  {
    id: 3,
    name: 'Carrot',
    mana: 1,
    attack: 1,
    defense: 2,
    portrait: 'https://i.imgur.com/smdtY1Y.jpg',
    description: 'Carrot is a low-cost card with relatively low attack but decent defense. It can serve as a cheap defensive option in battles, absorbing damage from enemy attacks.',
    cardImage: '/cards/6.png',
    type: 'Minion',
  },
  {
    id: 4,
    name: 'The Wizard Frog',
    mana: 3,
    attack: 4,
    defense: 3,
    portrait: 'https://i.imgur.com/JkZwHJG.jpg',
    description: 'The Wizard Frog is a magical creature with impressive attack and defense capabilities. With a mana cost of 3, it can be a key player in battles, casting powerful spells and conjuring defensive shields.',
    cardImage: '/cards/7.png',
    type: 'Minion',
  },
  {
    id: 5,
    name: 'Corgi',
    mana: 2,
    attack: 3,
    defense: 2,
    portrait: '/corgi.jpg',
    description: 'Corgi is a charming and agile card with moderate attack and defense abilities. With a mana cost of 2, it can swiftly navigate the battlefield and deliver swift strikes to opponents.',
    cardImage: '/cards/8.png',
    type: 'Minion',
  },
  {
    id: 6,
    name: 'Octopus',
    mana: 2,
    attack: 3,
    defense: 2,
    portrait: 'https://i.imgur.com/oEO2hjC.jpg',
    description: 'Octopus is a versatile creature that excels at adapting to different situations. With a mana cost of 2, it can use its tentacles to both attack and defend, providing flexibility in battles.',
    cardImage: '/cards/9.png',
    type: 'Minion',
  },
  {
    id: 7,
    name: 'SSS Snake',
    mana: 2,
    attack: 3,
    defense: 2,
    portrait: 'https://i.imgur.com/98C2bwX.jpg',
    description: 'The SSS Snake is a stealthy and cunning card. With a mana cost of 2, it can strike swiftly and silently, bypassing enemy defenses. It has moderate attack and defense capabilities.',
    cardImage: '/cards/10.png',
    type: 'Minion',
  },
  {
    id: 8,
    name: 'The onion',
    mana: 3,
    attack: 4,
    defense: 3,
    portrait: 'https://i.imgur.com/JXVC7lU.png?1',
    description: 'The onion is a card with a peculiar set of abilities. With a mana cost of 3, it can make opponents shed tears with its potent attack and defense capabilities. It possesses an aura of protection that reduces incoming damage.',
    cardImage: '/cards/11.png',
    type: 'Minion',
  },
  {
    id: 9,
    name: 'Twin Mushrooms',
    mana: 4,
    attack: 5,
    defense: 2,
    portrait: 'https://i.imgur.com/g5lp5nC.jpg',
    description: 'Twin Mushrooms are a unique duo that act as a single card. With a mana cost of 4, they possess high attack power but relatively low defense. Their combined strength makes them a formidable force on the battlefield.',
    cardImage: '/cards/12.png',
    type: 'Minion',
  },
  {
    id: 10,
    name: 'Booo',
    mana: 4,
    attack: 5,
    defense: 3,
    portrait: 'https://i.imgur.com/xD2yWMl.jpg',
    description: 'Booo is a card that harnesses the power of fear. With a mana cost of 4, it can intimidate opponents with its haunting presence, reducing their attack power. It possesses high attack and decent defense abilities.',
    cardImage: '/cards/13.png',
    type: 'Minion',
  },
  {
    id: 11,
    name: 'Bee Bee',
    mana: 4,
    attack: 5,
    defense: 3,
    portrait: 'https://i.imgur.com/3RB2DYl.jpg',
    description: 'Bee Bee is a buzzing card that commands the power of a swarm. With a mana cost of 4, it can overwhelm opponents with its high attack and disrupt their strategies. It has decent defense to withstand retaliation.',
    cardImage: '/cards/14.png',
    type: 'Minion',
  },
  {
    id: 12,
    name: 'Poison Flower',
    mana: 5,
    attack: 5,
    defense: 4,
    portrait: 'https://i.imgur.com/6X8bwdM.jpg',
    description: 'The Poison Flower is a sinister and deadly card. With a mana cost of 5, it can poison enemies with its toxic attacks, gradually wearing them down. It possesses high attack and defense capabilities.',
    cardImage: '/cards/15.png',
    type: 'Minion',
  },
  {
    id: 13,
    name: 'The Sea Friends',
    mana: 3,
    attack: 4,
    defense: 3,
    portrait: 'https://i.imgur.com/zXnQO6n.jpg',
    description: 'The Sea Friends are a group of aquatic creatures that work together to defend the ocean. With a mana cost of 3, they have moderate attack and defense abilities. They excel in battles near water-based environments.',
    cardImage: '/cards/16.png',
    type: 'Minion',
  },
  {
    id: 14,
    name: 'Angry Cat',
    mana: 3,
    attack: 3,
    defense: 3,
    portrait: 'https://i.imgur.com/uSlX1eM.jpg',
    description: 'The Angry Cat is a ferocious feline with a short temper. With a mana cost of 3, it can unleash its fury on opponents, dealing significant damage. It possesses balanced attack and defense capabilities.',
    cardImage: '/cards/17.png',
    type: 'Minion',
  },
  {
    id: 15,
    name: 'Rocket',
    mana: 4,
    attack: 5,
    defense: 3,
    portrait: 'https://i.imgur.com/fXhdKwB.jpg',
    description: 'Rocket is an explosive card that brings firepower to the battlefield. With a mana cost of 4, it launches devastating attacks, obliterating enemy defenses. It has high attack power but relatively low defense.',
    cardImage: '/cards/18.png',
    type: 'Minion',
  },
  {
    id: 16,
    name: 'Axolotl',
    mana: 3,
    attack: 3,
    defense: 2,
    portrait: '/portraits/19.jpg',
    description: 'Axolotl is a unique aquatic creature known for its regenerative abilities. With a mana cost of 3, it can regenerate its health, making it difficult to defeat. It has moderate attack and defense capabilities.',
    cardImage: '/cards/19.png',
    type: 'Minion',
  },
  {
    id: 17,
    name: 'Seal',
    mana: 2,
    attack: 2,
    defense: 4,
    portrait: '/portraits/20.jpg',
    description: 'Seal is a resilient creature that thrives in icy environments. With a mana cost of 2, it possesses high defense and can withstand powerful enemy attacks. Its attack power is moderate.',
    cardImage: '/cards/20.png',
    type: 'Minion',
  },
  {
    id: 18,
    name: 'Crocodile',
    mana: 3,
    attack: 4,
    defense: 5,
    portrait: '/portraits/21.jpg',
    description: 'Crocodile is a fearsome reptile that lurks in swamps and rivers. With a mana cost of 3, it has high attack and defense capabilities, making it a formidable force in battles.',
    cardImage: '/cards/21.png',
    type: 'Minion',
  },
  {
    id: 19,
    name: 'Giraffe',
    mana: 3,
    attack: 3,
    defense: 4,
    portrait: '/portraits/22.jpg',
    description: 'Giraffe is a tall and graceful creature with a long neck. With a mana cost of 3, it possesses moderate attack and defense capabilities. Its height allows it to see distant enemies and plan strategic moves.',
    cardImage: '/cards/22.jpg',
    type: 'Minion',
  },
  {
    id: 20,
    name: 'Capybara',
    mana: 2,
    attack: 2,
    defense: 3,
    portrait: '/portraits/23.jpg',
    description: 'Capybara is a friendly and sociable creature found in the wild. With a mana cost of 2, it has moderate attack and defense capabilities. Its friendly nature can sometimes influence the actions of opponents.',
    cardImage: '/cards/23.png',
    type: 'Minion',
  },
  {
    id: 21,
    name: 'Pufferfish',
    mana: 2,
    attack: 3,
    defense: 1,
    portrait: '/portraits/24.jpg',
    description: 'Pufferfish is a small but dangerous aquatic creature. With a mana cost of 2, it can inflate itself and release toxic spikes, causing damage to opponents. Its defense is relatively low.',
    cardImage: '/cards/24.png',
    type: 'Minion',
  },
  {
    id: 22,
    name: 'Otter',
    mana: 3,
    attack: 3,
    defense: 3,
    portrait: '/portraits/25.jpg',
    description: 'Otter is an agile and playful creature that excels in aquatic environments. With a mana cost of 3, it has balanced attack and defense capabilities. It can swiftly navigate water-based battlegrounds.',
    cardImage: '/cards/25.png',
    type: 'Minion',
  },
  {
    id: 23,
    name: 'Cactus',
    mana: 1,
    attack: 1,
    defense: 4,
    portrait: '/portraits/26.jpg',
    description: 'Cactus is a desert-dwelling plant with thorny defenses. With a mana cost of 1, it has low attack but high defense, making it a resilient barrier against enemy attacks.',
    cardImage: '/cards/26.png',
    type: 'Minion',
  },
  {
    id: 24,
    name: 'Penguin',
    mana: 2,
    attack: 2,
    defense: 2,
    portrait: '/portraits/27.jpg',
    description: 'Penguin is a cute and waddling creature found in icy regions. With a mana cost of 2, it has balanced attack and defense capabilities. Its charming appearance can sometimes distract opponents.',
    cardImage: '/cards/27.png',
    type: 'Minion',
  },
  {
    id: 25,
    name: 'Duck',
    mana: 1,
    attack: 1,
    defense: 1,
    portrait: '/portraits/28.jpg',
    description: 'Duck is a small and agile bird commonly seen near water bodies. With a mana cost of 1, it has low attack and defense capabilities. Its small size allows it to evade some attacks.',
    cardImage: '/cards/28.png',
    type: 'Minion',
  },
  {
    id: 26,
    name: 'Seahorse',
    mana: 2,
    attack: 1,
    defense: 3,
    portrait: '/portraits/29.jpg',
    description: 'Seahorse is a unique aquatic creature known for its elegant appearance. With a mana cost of 2, it has low attack but moderate defense capabilities. It can gracefully maneuver through water-based battles.',
    cardImage: '/cards/29.png',
    type: 'Minion',
  },
  {
    id: 27,
    name: 'Coconut',
    mana: 1,
    attack: 1,
    defense: 2,
    portrait: '/portraits/30.jpg',
    description: 'Coconut is a solid and hard-shelled fruit that can provide protective cover. With a mana cost of 1, it has no attack power but offers decent defense. It can be used strategically to shield other minions.',
    cardImage: '/cards/30.png',
    type: 'Minion',
  },
  {
    id: 28,
    name: 'Seashell',
    mana: 1,
    attack: 3,
    defense: 1,
    portrait: '/portraits/31.jpg',
    description: 'Seashell is a beautiful shell found on beaches. With a mana cost of 1, it has no attack power and low defense. It serves as a decorative piece rather than a formidable minion.',
    cardImage: '/cards/31.png',
    type: 'Minion',
  },
  {
    id: 29,
    name: 'French Duck',
    mana: 3,
    attack: 2,
    defense: 2,
    portrait: '/portraits/32.jpg',
    description: 'French Duck is a sophisticated avian with refined tastes. With a mana cost of 3, it has moderate attack and defense capabilities. Its elegant demeanor can sometimes influence the outcome of battles.',
    cardImage: '/cards/32.png',
    type: 'Minion',
  },
  {
    id: 30,
    name: 'Shark',
    mana: 5,
    attack: 6,
    defense: 5,
    portrait: '/portraits/33.jpg',
    description: 'Shark is a fearsome predator of the deep sea. With a mana cost of 5, it possesses high attack and defense capabilities, making it a formidable force in aquatic battles.',
    cardImage: '/cards/33.png',
    type: 'Minion',
  },
  {
    id: 31,
    name: 'Koala',
    mana: 3,
    attack: 2,
    defense: 4,
    portrait: '/portraits/34.jpg',
    description: 'Koala is an adorable and sleepy creature found in trees. With a mana cost of 3, it has moderate attack and high defense capabilities. Its relaxed nature can sometimes surprise opponents.',
    cardImage: '/cards/34.png',
    type: 'Minion',
  },
  {
    id: 32,
    name: 'Fox',
    mana: 3,
    attack: 4,
    defense: 2,
    portrait: '/portraits/35.jpg',
    description: 'Fox is a cunning and agile creature known for its slyness. With a mana cost of 3, it has high attack and moderate defense capabilities. Its strategic maneuvers can outwit opponents.',
    cardImage: '/cards/35.png',
    type: 'Minion',
  },
  {
    id: 33,
    name: 'Deer',
    mana: 4,
    attack: 3,
    defense: 3,
    portrait: '/portraits/36.jpg',
    description: 'Deer is a graceful and swift creature of the forest. With a mana cost of 4, it has balanced attack and defense capabilities. Its agility allows it to evade enemy attacks.',
    cardImage: '/cards/36.png',
    type: 'Minion',
  },
  {
    id: 34,
    name: 'Chameleon',
    mana: 2,
    attack: 1,
    defense: 1,
    portrait: '/portraits/37.jpg',
    description: 'Chameleon is a master of camouflage and adaptation. With a mana cost of 2, it has low attack and defense capabilities. Its ability to blend in with the environment can sometimes confuse opponents.',
    cardImage: '/cards/37.png',
    type: 'Minion',
  },
  {
    id: 35,
    name: 'Sloth',
    mana: 1,
    attack: 1,
    defense: 3,
    portrait: '/portraits/38.jpg',
    description: 'Sloth is a slow-moving creature known for its laziness. With a mana cost of 1, it has no attack power but offers high defense. Its relaxed nature can sometimes frustrate opponents.',
    cardImage: '/cards/38.png',
    type: 'Minion',
  },
  {
    id: 36,
    name: 'Parrot',
    mana: 2,
    attack: 2,
    defense: 2,
    portrait: '/portraits/39.jpg',
    description: 'Parrot is a colorful and talkative bird found in tropical regions. With a mana cost of 2, it has balanced attack and defense capabilities. Its mimicry can sometimes confuse opponents.',
    cardImage: '/cards/39.png',
    type: 'Minion',
  },
  {
    id: 37,
    name: 'Dinosaur',
    mana: 6,
    attack: 7,
    defense: 6,
    portrait: '/portraits/40.jpg',
    description: 'Dinosaur is a prehistoric creature with immense size and strength. With a mana cost of 6, it possesses high attack and defense capabilities, making it a dominant force on the battlefield.',
    cardImage: '/cards/40.png',
    type: 'Minion',
  },
  {
    id: 38,
    name: 'Goldfish',
    mana: 1,
    attack: 1,
    defense: 1,
    portrait: '/portraits/41.jpg',
    description: 'Goldfish is a small and shiny fish commonly kept as a pet. With a mana cost of 1, it has low attack and defense capabilities. Its vibrant colors can sometimes distract opponents.',
    cardImage: '/cards/41.png',
    type: 'Minion',
  },
  {
    id: 39,
    name: 'Elephant',
    mana: 5,
    attack: 4,
    defense: 7,
    portrait: '/portraits/42.jpg',
    description: 'Elephant is a majestic and powerful creature of the wild. With a mana cost of 5, it possesses high defense and moderate attack capabilities. Its immense size provides a formidable presence on the battlefield.',
    cardImage: '/cards/42.png',
    type: 'Minion',
  },
  {
    id: 40,
    name: 'Ebi Fry',
    mana: 2,
    attack: 3,
    defense: 1,
    portrait: '/portraits/43.jpg',
    description: 'Ebi Fry is a delicious breaded shrimp dish. With a mana cost of 2, it has moderate attack but low defense capabilities. It can be used strategically as a quick offensive option.',
    cardImage: '/cards/43.png',
    type: 'Minion',
  },
];

export function newRandomCard() {
  const randomCard = cards[Math.floor(Math.random() * cards.length)];
  return randomCard;
}
